const express=require("express");
const router=express.Router();
const {requireAuth}=require("../../middleware/apiAuth");
const adminApi=require("../../controllers/api/adminApiController");
router.use(requireAuth);
router.get("/dashboard",adminApi.dashboard);
router.post("/application/:id/approve",adminApi.approveApplication);
router.post("/application/:id/reject",adminApi.rejectApplication);
router.post("/manga/:id/approve",adminApi.approveManga);
router.post("/manga/:id/reject",adminApi.rejectManga);
router.post("/user/:id/ban",adminApi.banUser);
router.post("/user/:id/unban",adminApi.unbanUser);
router.delete("/user/:id",adminApi.deleteUser);
router.post("/comment/:id/toggle-hide",adminApi.toggleHideComment);
router.post("/chapter/:id/toggle-hide",adminApi.toggleHideChapter);
router.delete("/chapter/:id",adminApi.deleteChapter);
router.post("/category",adminApi.createCategory);
router.delete("/category/:id",adminApi.deleteCategory);
module.exports=router;
